name: Ansible Lint # feel free to pick your own name
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6.3.0

